// Code generated by "stringer -type Types"; DO NOT EDIT.

package through

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypesUnknown-0]
	_ = x[TypesClient-1]
	_ = x[TypesServer-2]
}

const _Types_name = "TypesUnknownTypesClientTypesServer"

var _Types_index = [...]uint8{0, 12, 23, 34}

func (i Types) String() string {
	if i >= Types(len(_Types_index)-1) {
		return "Types(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Types_name[_Types_index[i]:_Types_index[i+1]]
}
